add JASC-PAL support when importing palettes
Kawa-oneechan/SCICompanion pull request #24
Opened 2024-03-08 04:39 UTC by clarkjoe

## Overview
Add `JASC-PAL` support when importing palettes.

Currently, only `RIFF-PAL` palettes are supported. These are binary files and difficult for human reading. `JASC-PAL` are palette files that are human readable.

They have the following format according to [this source](https://liero.nl/lierohack/docformats/other-jasc.html):
>This file works like this: The PAL file is a text file, so NO binary data.
The first line of data contains the text `JASC-PAL`.
The second line contains the text `0100`--can skip over.
The third line contains a number. This is the number of colors in the palette, most likely 256 colors.
>After that, there are lines of text, containing 3 numbers per line, with spaces between them.
These numbers are respectively the Red, Green and Blue values (the so-called RGB palette). For example, the color white would be '255 255 255' and black '0 0 0' (255 is the most bright, 0 the less bright)

2024-03-08 08:45 UTC, Kawa-oneechan requested changes
Seems to work, even on my old PSP8 files, but I'd suggest finding the filter list in `PaletteDefinitionDialog` and adding `PspPalette` to it, makes things more discoverable.

2024-03-09 19:26 UTC, clarkjoe commented
What is the PSP8 file extension? `.psp8` or `.psp`? I think `.psp` file extension would suffice.

2024-03-09 19:30 UTC, clarkjoe commented
Added `.psp` to the list. Should be good to merge now.

2024-03-09 23:15 UTC, Kawa-oneechan commented
The extension for PSP palettes is `PspPalette`, sorry if that wasn't clear.

Besides, PSP gas lot of bespoke file formats and having just `Psp` for an extension would make it hard to tell an image from a palette.

2024-03-10 02:18 UTC, clarkjoe commented
Sounds good. Just updated with `PspPalette` as the file extension.

2024-03-10 14:49 UTC, Kawa-oneechan approved these changes

2024-03-10 14:49 UTC, merged